In [1]:
import numpy as np


In [5]:
arra=np.arange(0,10)
arra

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
arra=np.arange(0,20)

arra

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [14]:
data=np.random.randint(0,100,(5,5))
data

array([[67, 52, 96, 80, 32],
       [28, 52, 13, 40, 29],
       [45, 61, 58, 41,  5],
       [77, 86, 10, 29, 45],
       [ 9, 56, 10, 58, 68]])

In [29]:
np.random.seed(122)

res=np.random.randint(1,100,(6,6))
res

array([[27, 11, 55, 77, 63, 17],
       [16, 60, 99, 80, 63, 55],
       [43, 22, 32, 42, 71, 79],
       [36, 96, 52, 20, 14, 33],
       [46, 21, 16, 82, 61, 76],
       [64, 43,  7, 49, 86, 41]])

In [30]:
res.reshape(18,2)
#res.min()

array([[27, 11],
       [55, 77],
       [63, 17],
       [16, 60],
       [99, 80],
       [63, 55],
       [43, 22],
       [32, 42],
       [71, 79],
       [36, 96],
       [52, 20],
       [14, 33],
       [46, 21],
       [16, 82],
       [61, 76],
       [64, 43],
       [ 7, 49],
       [86, 41]])

In [31]:
res.argmax()

8