In [26]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt
import numpy as np
import statsmodels.api as sm
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
from sklearn.compose import ColumnTransformer

In [27]:
data= pd.read_csv("startups_data.csv")

In [28]:
data.rename(columns={"R&D Spend":"RD_Spend"},inplace=True)

In [29]:
x_real=data.iloc[:,0:4].values
y_real=data.iloc[:,4].values

In [30]:
#la=LabelEncoder()
#x_real[:,3]=la.fit_transform(x_real[:,3])

oneHE=ColumnTransformer( [('one_hot_encoder', OneHotEncoder(categories='auto'), [3])], remainder='passthrough')

x_real=oneHE.fit_transform(x_real)

x_real=x_real[:,1:]

In [31]:
training_x,testing_x,training_y,testing_y= train_test_split(x_real,y_real,test_size=0.3,random_state=0) 

MLR= LinearRegression()

MLR.fit(training_x,training_y)

Predict_y= MLR.predict(testing_x)

XX=testing_x

In [32]:
Predict_y

array([104282.76472171, 132536.88499212, 133910.85007767,  72584.77489417,
       179920.9276189 , 114549.31079234,  66444.43261347,  98404.96840122,
       114499.82808602, 169367.50639895,  96522.62539981,  88040.67182871,
       110949.99405525,  90419.1897851 , 128020.46250064])

In [33]:
testing_y

array([103282.38, 144259.4 , 146121.95,  77798.83, 191050.39, 105008.31,
        81229.06,  97483.56, 110352.25, 166187.94,  96778.92,  96479.51,
       105733.54,  96712.8 , 124266.9 ])

In [34]:
acq=Predict_y.sum()/testing_y.sum()
acq

0.9757333804563337

In [35]:
x_real=np.append(arr=np.ones((50,1)).astype(int),values=x_real,axis=1)

In [38]:
x_real

array([[1, 0.0, 1.0, 165349.2, 136897.8, 471784.1],
       [1, 0.0, 0.0, 162597.7, 151377.59, 443898.53],
       [1, 1.0, 0.0, 153441.51, 101145.55, 407934.54],
       [1, 0.0, 1.0, 144372.41, 118671.85, 383199.62],
       [1, 1.0, 0.0, 142107.34, 91391.77, 366168.42],
       [1, 0.0, 1.0, 131876.9, 99814.71, 362861.36],
       [1, 0.0, 0.0, 134615.46, 147198.87, 127716.82],
       [1, 1.0, 0.0, 130298.13, 145530.06, 323876.68],
       [1, 0.0, 1.0, 120542.52, 148718.95, 311613.29],
       [1, 0.0, 0.0, 123334.88, 108679.17, 304981.62],
       [1, 1.0, 0.0, 101913.08, 110594.11, 229160.95],
       [1, 0.0, 0.0, 100671.96, 91790.61, 249744.55],
       [1, 1.0, 0.0, 93863.75, 127320.38, 249839.44],
       [1, 0.0, 0.0, 91992.39, 135495.07, 252664.93],
       [1, 1.0, 0.0, 119943.24, 156547.42, 256512.92],
       [1, 0.0, 1.0, 114523.61, 122616.84, 261776.23],
       [1, 0.0, 0.0, 78013.11, 121597.55, 264346.06],
       [1, 0.0, 1.0, 94657.16, 145077.58, 282574.31],
       [1, 1.0, 0.0, 9

In [11]:
X_opt = np.array(x_real[:, [0, 1, 2, 3, 4, 5]], dtype=float)

y_real

array([192261.83, 191792.06, 191050.39, 182901.99, 166187.94, 156991.12,
       156122.51, 155752.6 , 152211.77, 149759.96, 146121.95, 144259.4 ,
       141585.52, 134307.35, 132602.65, 129917.04, 126992.93, 125370.37,
       124266.9 , 122776.86, 118474.03, 111313.02, 110352.25, 108733.99,
       108552.04, 107404.34, 105733.54, 105008.31, 103282.38, 101004.64,
        99937.59,  97483.56,  97427.84,  96778.92,  96712.8 ,  96479.51,
        90708.19,  89949.14,  81229.06,  81005.76,  78239.91,  77798.83,
        71498.49,  69758.98,  65200.33,  64926.08,  49490.75,  42559.73,
        35673.41,  14681.4 ])

In [12]:
reg_OLS=sm.OLS(endog=y_real,exog=X_opt).fit()

In [13]:
reg_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.951
Model:                            OLS   Adj. R-squared:                  0.945
Method:                 Least Squares   F-statistic:                     169.9
Date:                Sun, 16 Aug 2020   Prob (F-statistic):           1.34e-27
Time:                        01:13:08   Log-Likelihood:                -525.38
No. Observations:                  50   AIC:                             1063.
Df Residuals:                      44   BIC:                             1074.
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       5.013e+04   6884.820      7.281      0.000    3.62e+04     6.4e+04
x1           198.7888   3371.007      0.059      0.953   -6595.030    6992.607
x2           -41.8870   3256.039     -0.013      0.990   -6604.003    6520.229
x3             0.8060      0.046     17.369      0.000       0.712       0.900
x4            -0.0270      0.052     -0.517      0.608      -0.132       0.078
x5             0.0270      0.017      1.574      0.123      -0.008       0.062
==============================================================================
Omnibus:                       14.782   Durbin-Watson:                   1.283
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               21.266
Skew:                          -0.948   Prob(JB):                     2.41e-05
Kurtosis:                       5.572   Cond. No.                     1.45e+06
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.45e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [14]:
X_opt = np.array(x_real[:, [0, 3]], dtype=float)
reg_OLS=sm.OLS(endog=y_real,exog=X_opt).fit()
reg_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.947
Model:                            OLS   Adj. R-squared:                  0.945
Method:                 Least Squares   F-statistic:                     849.8
Date:                Sun, 16 Aug 2020   Prob (F-statistic):           3.50e-32
Time:                        01:13:08   Log-Likelihood:                -527.44
No. Observations:                  50   AIC:                             1059.
Df Residuals:                      48   BIC:                             1063.
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       4.903e+04   2537.897     19.320      0.000    4.39e+04    5.41e+04
x1             0.8543      0.029     29.151      0.000       0.795       0.913
==============================================================================
Omnibus:                       13.727   Durbin-Watson:                   1.116
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               18.536
Skew:                          -0.911   Prob(JB):                     9.44e-05
Kurtosis:                       5.361   Cond. No.                     1.65e+05
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.65e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [15]:
training_x,testing_x,training_y,testing_y= train_test_split(X_opt,y_real,test_size=0.3,random_state=0) 

MLR= LinearRegression()

MLR.fit(training_x,training_y)

Predict_y= MLR.predict(testing_x)

testing_x

array([[1.0000000e+00, 6.6051520e+04],
       [1.0000000e+00, 1.0067196e+05],
       [1.0000000e+00, 1.0191308e+05],
       [1.0000000e+00, 2.7892920e+04],
       [1.0000000e+00, 1.5344151e+05],
       [1.0000000e+00, 7.2107600e+04],
       [1.0000000e+00, 2.0229590e+04],
       [1.0000000e+00, 6.1136380e+04],
       [1.0000000e+00, 7.3994560e+04],
       [1.0000000e+00, 1.4210734e+05],
       [1.0000000e+00, 5.5493950e+04],
       [1.0000000e+00, 4.6014020e+04],
       [1.0000000e+00, 7.5328870e+04],
       [1.0000000e+00, 4.6426070e+04],
       [1.0000000e+00, 9.1749160e+04]])

In [16]:
Predict_y

array([104347.29054818, 134059.15325094, 135124.30398379,  71598.91750239,
       179346.89726824, 109544.72355241,  65022.1146424 , 100129.03206143,
       111164.14538661, 169619.71578557,  95286.60066917,  87150.76014861,
       112309.27339546,  87504.38861279, 126401.4513695 ])

In [17]:
testing_y

array([103282.38, 144259.4 , 146121.95,  77798.83, 191050.39, 105008.31,
        81229.06,  97483.56, 110352.25, 166187.94,  96778.92,  96479.51,
       105733.54,  96712.8 , 124266.9 ])

In [18]:
acq=Predict_y.sum()/testing_y.sum()

In [19]:
acq

0.9689358174402832