In [88]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt
import numpy as np
import statsmodels.api as sm
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
from sklearn.compose import ColumnTransformer
from backwardElimination import *

In [89]:
data=pd.read_csv("CarPrice_Data.csv")

In [111]:
x_real=data.iloc[:,[6,14,15,16,17,19,21,22,23,24]].values
y_real=data.iloc[:,25].values

In [91]:
x_real
temp=pd.DataFrame(x_real)
temp

0     1     2    3     4     5    6     7   8   9
0    convertible  dohc  four  130  mpfi  2.68  111  5000  21  27
1    convertible  dohc  four  130  mpfi  2.68  111  5000  21  27
2      hatchback  ohcv   six  152  mpfi  3.47  154  5000  19  26
3          sedan   ohc  four  109  mpfi   3.4  102  5500  24  30
4          sedan   ohc  five  136  mpfi   3.4  115  5500  18  22
..           ...   ...   ...  ...   ...   ...  ...   ...  ..  ..
200        sedan   ohc  four  141  mpfi  3.15  114  5400  23  28
201        sedan   ohc  four  141  mpfi  3.15  160  5300  19  25
202        sedan  ohcv   six  173  mpfi  2.87  134  5500  18  23
203        sedan   ohc   six  145   idi   3.4  106  4800  26  27
204        sedan   ohc  four  141  mpfi  3.15  114  5400  19  25

[205 rows x 10 columns]

In [92]:
oneHE=ColumnTransformer( [('one_hot_encoder', OneHotEncoder(categories='auto'), [0,1,2,4])], remainder='passthrough')

x_real=oneHE.fit_transform(x_real)

x_real=x_real[:,1:]

In [93]:
training_x,testing_x,training_y,testing_y= train_test_split(x_real,y_real,test_size=0.3,random_state=0) 

MLR= LinearRegression()

MLR.fit(training_x,training_y)

Predict_y= MLR.predict(testing_x)

In [94]:
Predict_y

array([ 5771.83840214, 20518.64453976, 18591.28467252,  2739.54274311,
       10724.81114205, 13359.10708846,  5633.58688054,  6118.32625806,
       16858.53062572,  7137.93410696, 22480.23130862, 45442.41609524,
       12745.        , 13066.93719639,  6398.59943438, 14286.53009934,
        9611.85881545, 18010.80400486,  9195.65502201,  5755.66638238,
        8850.93063789, 16951.52223783,  9635.57691401, 14286.53009934,
       22087.9286689 ,  7367.44260225,  7666.39242342, 16371.04157017,
        7302.81884144,  6765.76075279,  9263.51583183,  9486.66944255,
       20260.69007193,  8608.84384557,  6765.76075279, 33369.84817998,
       13016.64895779, 13598.9860481 ,  6101.28658911, 39423.29164837,
        6398.59943438, 18973.42036296, 31881.39582   , 18838.28821796,
       11186.62097069,  7639.37612729,  6658.04915822, 13960.96062992,
       10602.63642949,  9263.51583183, 20040.10005628,  8431.52518976,
        7729.62079461,  9617.77847533, 19999.17732079, 16858.53062572,
      

In [95]:
testing_y

array([ 6795. , 15750. , 15250. ,  5151. ,  9995. , 11199. ,  5389. ,
        7898. , 17199. ,  6529. , 20970. , 31400.5, 10945. , 18344. ,
        8916.5,  9989. ,  9295. , 18920. ,  7895. ,  6488. ,  9959. ,
       15580. ,  9895. , 11549. , 15998. ,  5118. ,  6938. , 16695. ,
        8358. ,  5499. ,  7975. , 12290. , 22018. ,  8948. ,  6849. ,
       41315. , 11595. , 18150. ,  6377. , 45400. ,  8916.5, 17450. ,
       34184. , 15040. , 11259. ,  7609. ,  7609. , 14869. , 11694. ,
        8495. , 23875. ,  7099. ,  8058. , 10595. , 16503. , 18399. ,
       10795. , 18420. ,  9960. ,  6229. ,  6479. , 15510. ])

In [96]:
x_real=np.append(arr=np.ones((205,1)).astype(int),values=x_real,axis=1)

x_real
t=pd.DataFrame(x_real)
t

0  1  2  3  4  5  6  7  8  9   ... 23 24 25 26   27    28   29    30  31  \
0    1  0  0  0  0  1  0  0  0  0  ...  0  1  0  0  130  2.68  111  5000  21   
1    1  0  0  0  0  1  0  0  0  0  ...  0  1  0  0  130  2.68  111  5000  21   
2    1  0  1  0  0  0  0  0  0  0  ...  0  1  0  0  152  3.47  154  5000  19   
3    1  0  0  1  0  0  0  0  1  0  ...  0  1  0  0  109   3.4  102  5500  24   
4    1  0  0  1  0  0  0  0  1  0  ...  0  1  0  0  136   3.4  115  5500  18   
..  .. .. .. .. .. .. .. .. .. ..  ... .. .. .. ..  ...   ...  ...   ...  ..   
200  1  0  0  1  0  0  0  0  1  0  ...  0  1  0  0  141  3.15  114  5400  23   
201  1  0  0  1  0  0  0  0  1  0  ...  0  1  0  0  141  3.15  160  5300  19   
202  1  0  0  1  0  0  0  0  0  0  ...  0  1  0  0  173  2.87  134  5500  18   
203  1  0  0  1  0  0  0  0  1  0  ...  0  0  0  0  145   3.4  106  4800  26   
204  1  0  0  1  0  0  0  0  1  0  ...  0  1  0  0  141  3.15  114  5400  19   

     32  
0    27  
1    27  
2    26  
3    30  
4    22  
..   ..  
200  28  
201  25  
202  23  
203  27  
204  25  

[205 rows x 33 columns]

In [97]:
X_opt = np.array(x_real[:, :], dtype=float)

In [98]:
reg_OLS=sm.OLS(endog=y_real,exog=X_opt).fit()

In [99]:
reg_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.926
Model:                            OLS   Adj. R-squared:                  0.914
Method:                 Least Squares   F-statistic:                     78.19
Date:                Sun, 16 Aug 2020   Prob (F-statistic):           1.52e-84
Time:                        02:34:05   Log-Likelihood:                -1866.2
No. Observations:                 205   AIC:                             3790.
Df Residuals:                     176   BIC:                             3887.
Df Model:                          28                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const      -1965.3325   3536.872     -0.556      0.579   -8945.471    5014.806
x1         -3849.5133   1335.967     -2.881      0.004   -6486.090   -1212.936
x2         -3216.3255   1085.558     -2.963      0.003   -5358.711   -1073.940
x3         -2323.3698   1051.535     -2.210      0.028   -4398.611    -248.128
x4         -2786.9731   1147.325     -2.429      0.016   -5051.258    -522.688
x5           975.4979   1109.906      0.879      0.381   -1214.941    3165.936
x6          -1.46e+04   3297.725     -4.428      0.000   -2.11e+04   -8094.387
x7          5115.8313   1154.899      4.430      0.000    2836.599    7395.064
x8          5580.6816    979.648      5.697      0.000    3647.312    7514.051
x9          2673.1978   1026.973      2.603      0.010     646.430    4699.965
x10        -4881.2070   1026.345     -4.756      0.000   -6906.735   -2855.679
x11         3173.2265   1244.252      2.550      0.012     717.652    5628.801
x12         9235.4367   1866.701      4.947      0.000    5551.437    1.29e+04
x13         -813.1084   1170.262     -0.695      0.488   -3122.660    1496.443
x14        -3969.0086    984.564     -4.031      0.000   -5912.080   -2025.938
x15         -388.5177    909.713     -0.427      0.670   -2183.867    1406.832
x16         1347.2115   2759.704      0.488      0.626   -4099.160    6793.583
x17        -1.055e+04   3096.983     -3.407      0.001   -1.67e+04   -4438.571
x18         3173.2265   1244.252      2.550      0.012     717.652    5628.801
x19          233.6958   1119.154      0.209      0.835   -1974.993    2442.385
x20          -43.2385    750.047     -0.058      0.954   -1523.483    1437.006
x21          -39.6117   2456.742     -0.016      0.987   -4888.076    4808.852
x22         4471.6452   1040.955      4.296      0.000    2417.285    6526.005
x23        -3753.2886   2289.424     -1.639      0.103   -8271.545     764.968
x24         -466.9078    722.409     -0.646      0.519   -1892.607     958.791
x25        -2619.9612   1082.663     -2.420      0.017   -4756.633    -483.289
x26          252.3343   2165.222      0.117      0.907   -4020.806    4525.474
x27          126.1291     15.813      7.976      0.000      94.922     157.337
x28        -4700.8851    842.015     -5.583      0.000   -6362.630   -3039.140
x29           75.6615     14.991      5.047      0.000      46.075     105.248
x30            1.7346      0.551      3.149      0.002       0.647       2.822
x31          -93.5141    138.424     -0.676      0.500    -366.699     179.671
x32           44.9027    123.865      0.363      0.717    -199.548     289.354
==============================================================================
Omnibus:                        7.766   Durbin-Watson:                   1.533
Prob(Omnibus):                  0.021   Jarque-Bera (JB):               10.339
Sk

In [106]:
SL = 0.05

def backwardElimination(x,y, SL):
    numVars = len(x[0])
    temp = np.zeros((205,32)).astype(int)
    for i in range(0, numVars):
        regressor_OLS = sm.OLS(y, x).fit()
        maxVar = max(regressor_OLS.pvalues).astype(float)
        adjR_before = regressor_OLS.rsquared_adj.astype(float)
        if maxVar > SL:
            for j in range(0, numVars - i):
                if (regressor_OLS.pvalues[j].astype(float) == maxVar):
                    temp[:,j] = x[:, j]
                    x = np.delete(x, j, 1)
                    tmp_regressor = sm.OLS(y, x).fit()
                    adjR_after = tmp_regressor.rsquared_adj.astype(float)
                    if (adjR_before >= adjR_after):
                        x_rollback = np.hstack((x, temp[:,[0,j]]))
                        x_rollback = np.delete(x_rollback, j, 1)
                        print (regressor_OLS.summary())
                        return x_rollback
                    else:
                        continue
    regressor_OLS.summary()
    return x

X_Modeled = backwardElimination(X_opt, y_real, SL)

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.926
Model:                            OLS   Adj. R-squared:                  0.916
Method:                 Least Squares   F-statistic:                     93.18
Date:                Sun, 16 Aug 2020   Prob (F-statistic):           2.12e-88
Time:                        02:39:36   Log-Likelihood:                -1866.3
No. Observations:                 205   AIC:                             3783.
Df Residuals:                     180   BIC:                             3866.
Df Model:                          24                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const      -2138.9297   3477.113     -0.615      0.5

In [107]:
training_x,testing_x,training_y,testing_y= train_test_split(X_opt,y_real,test_size=0.3,random_state=0) 

MLR= LinearRegression()

MLR.fit(training_x,training_y)

Predict_y= MLR.predict(testing_x)

In [108]:
Predict_y

array([ 5771.83840214, 20518.64453976, 18591.28467252,  2739.54274311,
       10724.81114205, 13359.10708846,  5633.58688054,  6118.32625806,
       16858.53062572,  7137.93410696, 22480.23130862, 45442.41609524,
       12745.        , 13066.93719639,  6398.59943438, 14286.53009934,
        9611.85881545, 18010.80400486,  9195.65502201,  5755.66638237,
        8850.93063789, 16951.52223783,  9635.57691401, 14286.53009934,
       22087.9286689 ,  7367.44260225,  7666.39242342, 16371.04157017,
        7302.81884144,  6765.76075279,  9263.51583183,  9486.66944255,
       20260.69007193,  8608.84384557,  6765.76075279, 33369.84817998,
       13016.64895779, 13598.9860481 ,  6101.28658912, 39423.29164837,
        6398.59943438, 18973.42036296, 31881.39582   , 18838.28821796,
       11186.62097069,  7639.37612729,  6658.04915822, 13960.96062992,
       10602.63642949,  9263.51583183, 20040.10005628,  8431.52518976,
        7729.62079461,  9617.77847533, 19999.17732079, 16858.53062572,
      

In [109]:
testing_y

array([ 6795. , 15750. , 15250. ,  5151. ,  9995. , 11199. ,  5389. ,
        7898. , 17199. ,  6529. , 20970. , 31400.5, 10945. , 18344. ,
        8916.5,  9989. ,  9295. , 18920. ,  7895. ,  6488. ,  9959. ,
       15580. ,  9895. , 11549. , 15998. ,  5118. ,  6938. , 16695. ,
        8358. ,  5499. ,  7975. , 12290. , 22018. ,  8948. ,  6849. ,
       41315. , 11595. , 18150. ,  6377. , 45400. ,  8916.5, 17450. ,
       34184. , 15040. , 11259. ,  7609. ,  7609. , 14869. , 11694. ,
        8495. , 23875. ,  7099. ,  8058. , 10595. , 16503. , 18399. ,
       10795. , 18420. ,  9960. ,  6229. ,  6479. , 15510. ])